audio:
  sr: 16000
  n_fft: 512
  num_freq: 257
  hop_length: 160
  win_length: 400
---
data:
  num_classes: 7
  train: 'datasets/meta/train'
  test: 'datasets/meta/test'
  file_format: '*-norm.wav'
---
train:
  num_workers: 16
  batch_size: 60
  optimizer: 'adam'
  adam:
    initlr: 0.0003
    lrdecay:
      epoch: 36
      gamma: 0.1
---
test:
  num_workers: 16
  batch_size: 64
---
model:
  temporal: 250
  cluster:
    K: 8
    G: 2
  dim: 512
  loss:
    scale: 1.0
    margin: 0.0
---
log:
  summary_interval: 1
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
