data:
  num_classes: 7
  train: 'dataset/meta/train'
  test: 'dataset/meta/test'
  file_format: '*.file_extension'
  use_background_generator: true
---
train:
  num_iter: 10000  # max iteration
  num_workers: 16
  batch_size: 64
  optimizer: 'adam'
  adam:
    initlr: 0.0003
    lrdecay:
      epoch: 36
      gamma: 0.1
---
test:
  num_workers: 16
  batch_size: 64
---
model:
  device: 'cuda'
---
log:
  name: 'Fisrt_training'
  use_tensorboard: true
  use_wandb: false
  wandb_init_conf:
    entity: ~
    project: ~
  summary_interval: 1
  chkpt_interval: 10
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
---
load:
  wandb_load_path: ~
  network_chkpt_path: ./test.pt
  strict_load: false
  resume_state_path: ~
